---
# tasks file for profile-n01580922
- name: Append lines to /etc/profile
  become: yes
  blockinfile:
    path: /etc/profile
    block: |
      {{ profile_comment }}
      export TMOUT={{ tmout_value }}
  tags:
    - profile-n01580922
